### ISSUE TITLE
Mod packaged improperly

### ISSUE THREAD

**Issue by Oricul** [Oricul/eso-RandomMount#10]
I left a comment on ESO.UI. The files aren't in their own "folder" when installing through Minion. The LibRandomMount, Localization folders and the manifest and LUA files get installed in the addons folder. ESO doesn't recognize the addon as being installed. I have moved my files in to a folder named RandomMount.
I also think that having the extra API versions in the manifest are making it state that it's out of date. If you change that text file to say 101037 101038 it removers the "out of date" in the addons list.

_Originally posted by @sshogrin in https://github.com/Oricul/eso-RandomMount/issues/6#issuecomment-1604303115_

**Comment by Oricul** [comment]
I've corrected this and re-uploaded 3.7.

**Comment by sshogrin** [comment]
It's also not pulling out the random mount when you have a companion out or when grouped.
I do understand that there's not really any documentation in the API for this. I wonder if Bertram can help out
